server:
  port: 8080

logging:
  level:
    mingu.learningspringboot: debug

management:
  endpoint:
    health:
      enabled: true

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: test
      password: test
      database: test
